Add logback, so we get test outputs...
retest/recheck-xml pull request #4
Opened 2018-08-09 12:42 UTC by roesslerj

2018-08-09 13:17 UTC, diba1013 requested changes

2018-08-09 13:17 UTC, diba1013 commented on pom.xml
> +			<artifactId>logback-classic</artifactId>
You should replace slf4j-api with this. Why only tests for production it does not work also... .

2018-08-09 13:17 UTC, diba1013 commented on src/test/resources/retest/logback.xml
> +<configuration debugging="false">
This is for retest for starting the gui.

2018-08-10 13:21 UTC, roesslerj commented on pom.xml
> +			<artifactId>logback-classic</artifactId>
No. We deliver an API. It should be up to the user, to determine his logging framework. We use a concrete logging framework only in our own tests.

2018-08-10 13:21 UTC, roesslerj commented on pom.xml
> +			<artifactId>logback-classic</artifactId>
But maybe this should be put into the readme somewhere...

2018-08-10 13:22 UTC, roesslerj commented on src/test/resources/retest/logback.xml
> +<configuration debugging="false">
Hmm. Does it hurt?

2018-08-10 16:49 UTC, diba1013 approved these changes

2018-08-10 21:46 UTC, merged